services:
  motion-detection:
    image: akshaykannan/homeassistant-camera-ai:latest
    ports:
      - "5427:5427"
    volumes:
      - ./config.yaml:/app/config.yaml
    environment:
      - GOOGLE_API_KEY=${GOOGLE_API_KEY}
      - HA_TOKEN=${HA_TOKEN}
    restart: unless-stopped
